name: Update README with blog posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install rss-parser@latest

      - name: Update README
        run: node update-readme.js

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
      
          if ! git diff --cached --quiet; then
            git commit -m "Updated README with latest blog posts"
      
            # Pull the latest changes from the remote main branch before pushing
            git pull origin main --rebase
      
            # Push the changes to main
            git push origin main
          else
            echo "No changes to commit."
          fi

