name: Update README with blog posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository with full history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install rss-parser@latest

      # Step 4: Pull the latest changes from the remote main branch
      - name: Pull latest changes
        run: git pull origin main --no-edit || git reset --hard origin/main

      # Step 5: Run the script to update README
      - name: Update README
        run: node update-readme.js

      # Step 6: Commit and push the changes if README.md was updated
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md

          if ! git diff --cached --quiet; then
            git commit -m "Updated README with latest blog posts"
            git push origin main
          else
            echo "No changes to commit."
          fi
