name: Update README with blog posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install rss-parser@latest
    - name: Update README
      run: |
        node update-readme.js
        cat README.md  # This will output the content of README.md to the action logs
      continue-on-error: true
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git diff --quiet || (git commit -m "Updated README with latest blog posts" && git pull --rebase && git push)
